--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VsrStudio/SimpleClothes
build-by-default: true
branches:
- main
projects:
  SimpleClothes:
    path: ""
    icon: "icon.png"
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.5
...
