name: SimpleClothes
api: 5.0.0
version: 1.0.0
main: VsrStudio\SimpleClothes\Main
author: VsrStudio
description: §bThis VsrSimpleClothes Dont Sell Bro
website: vsrstudio.web.id
commands:
  simpleclothes:
    description: "§bOpen SimpleClothes"
    permission: simpleclothes.use
    aliases: [sc, clothes]
permissions:
  simpleclothes.use:
    default: true
