name: SimpleClothes
api: 5.0.0
version: 1.2.0
main: VsrStudio\SimpleClothes\Main
author: VsrStudio
description: §bThis SimpleClothes Dont Sell Bro
website: vsrstudio.web.id
softdepend: [EconomyAPI, ScoreHud]
commands:
  simpleclothes:
    description: "§bOpen SimpleClothes"
    permission: simpleclothes.use
    aliases: [sc, clothes]
  scshop:
    description: "§bOpen SimpleClothes Shop"
    permission: scshop.use
  scmenu:
    description: "§bOpen SimpleClothes Menu"
    permission: scmenu.use
  sccrate:
    description: "§bOpen SimpleClothes Crate"
    permission: sccrate.use
  permission:
    description: "Simpleclothes permission"
    permission: permission.command
  scrca:
    description: "rca simpleclothes"
    permission: scrca.command
permissions:
  simpleclothes.use:
    default: true
  scshop.use:
    default: true
  scmenu.use:
    default: true
  sccrate.use:
    default: true
  setkey.command:
    default: op
  givekey.command:
    default: op
  takekey.command:
    default: op
  help.command:
    default: true
  permission.command:
    default: op
  scrca.command:
    default: op
  simpleclothes.portal:
    default: op
  simpleclothes.flame:
    default: op
  simpleclothes.explode:
    default: op
  simpleclothes.entityflame:
    default: op
  simpleclothes.water:
    default: op
  simpleclothes.waterdrip:
    default: op
  simpleclothes.lava:
    default: op
  simpleclothes.lavadrip:
    default: op
  simpleclothes.heart:
    default: op
  simpleclothes.angryvillager:
    default: op
  simpleclothes.happyvillager:
    default: op
  simpleclothes.critical:
    default: op
  simpleclothes.enchanttable:
    default: op
  simpleclothes.ink:
    default: op
  simpleclothes.spore:
    default: op
  simpleclothes.smoke:
    default: op
  simpleclothes.snowball:
    default: op
  simpleclothes.redstone:
    default: op
  simpleclothes.floatingtxt:
    default: op
