name: SimpleClothes
api: 5.0.0
version: 1.2.0
main: VsrStudio\SimpleClothes\Main
author: VsrStudio
description: §bSimpleClothes like cosmetic
website: vsrstudio.web.id
softdepend: [EconomyAPI, ScoreHud]
commands:
  simpleclothes:
    description: "§bOpen SimpleClothes"
    permission: simpleclothes.use
    aliases: [sc, clothes]
  scshop:
    description: "§bOpen SimpleClothes Shop"
    permission: simpleclothes.shop
  scmenu:
    description: "§bOpen SimpleClothes Menu"
    permission: simpleclothes.menu
  sccrate:
    description: "§bOpen SimpleClothes Crate"
    permission: simpleclothes.crate
  permission:
    description: "Simpleclothes permission"
    permission: simpleclothes.permission
  scrca:
    description: "rca simpleclothes"
    permission: simpleclothes.rca
permissions:
  simpleclothes.use:
    default: true
  simpleclothes.shop:
    default: true
  simpleclothes.menu:
    default: true
  simpleclothes.crate:
    default: true
  simpleclothes.setkey:
    default: op
  simpleclothes.givekey:
    default: op
  simpleclothes.takekey:
    default: op
  simpleclothes.help:
    default: op
  simpleclothes.permission:
    default: op
  simpleclothes.rca:
    default: op
  simpleclothes.portal:
    default: op
  simpleclothes.flame:
    default: op
  simpleclothes.explode:
    default: op
  simpleclothes.entityflame:
    default: op
  simpleclothes.water:
    default: op
  simpleclothes.waterdrip:
    default: op
  simpleclothes.lava:
    default: op
  simpleclothes.lavadrip:
    default: op
  simpleclothes.heart:
    default: op
  simpleclothes.angryvillager:
    default: op
  simpleclothes.happyvillager:
    default: op
  simpleclothes.critical:
    default: op
  simpleclothes.enchanttable:
    default: op
  simpleclothes.ink:
    default: op
  simpleclothes.spore:
    default: op
  simpleclothes.smoke:
    default: op
  simpleclothes.snowball:
    default: op
  simpleclothes.redstone:
    default: op
  simpleclothes.floatingtxt:
    default: op
