name: SimpleClothes
api: 5.0.0
version: 1.1.0
main: VsrStudio\SimpleClothes\Main
author: VsrStudio
description: §bOpen SimpleClothes
website: vsrstudio.web.id
commands:
  simpleclothes:
    description: "§bOpen SimpleClothes"
    permission: simpleclothes.use
    aliases: [sc, clothes]
permissions:
  simpleclothes.use:
    default: true
  simpleclothes.portal:
    default: op
  simpleclothes.flame:
    default: op
  simpleclothes.explode:
    default: op
  simpleclothes.entityflame:
    default: op
  simpleclothes.water:
    default: op
  simpleclothes.waterdrip:
    default: op
  simpleclothes.lava:
    default: op
  simpleclothes.lavadrip:
    default: op
  simpleclothes.heart:
    default: op
  simpleclothes.angryvillager:
    default: op
  simpleclothes.happyvillager:
    default: op
  simpleclothes.critical:
    default: op
  simpleclothes.enchanttable:
    default: op
  simpleclothes.ink:
    default: op
  simpleclothes.spore:
    default: op
  simpleclothes.smoke:
    default: op
  simpleclothes.snowball:
    default: op
  simpleclothes.redstone:
    default: op
  simpleclothes.floatingtxt:
    default: op
