name: SimpleClothes
api: 5.0.0
version: 1.1.0
main: VsrStudio\SimpleClothes\Main
author: VsrStudio
description: §bThis SimpleClothes Dont Sell Bro
website: vsrstudio.web.id
commands:
  simpleclothes:
    description: "§bOpen SimpleClothes"
    permission: simpleclothes.use
    aliases: [sc, clothes]
permissions:
  simpleclothes.use:
    default: true
  particle.portal:
    default: op
  particle.flame:
    default: op
  particle.explode:
    default: op
  particle.entityflame:
    default: op
  particle.water:
    default: op
  particle.waterdrip:
    default: op
  particle.lava:
    default: op
  particle.lavadrip:
    default: op
  particle.heart:
    default: op
  particle.angryvillager:
    default: op
  particle.happyvillager:
    default: op
  particle.critical:
    default: op
  particle.enchanttable:
    default: op
  particle.ink:
    default: op
  particle.spore:
    default: op
  particle.smoke:
    default: op
  particle.snowball:
    default: op
  particle.redstone:
    default: op
  particle.floatingtxt:
    default: op
