# Created By VsrStudio
# Config.yml SimpleCkothes Please Don't Delete Anything Here

DeleteSkinAfterQuitting: false

no-permissions: §cYou don't have Permissions for this action!

skin-resetted: §aYour Skin has been resetted!

cape-on: §aYou activated the {name}-Cape!

standard_capes: ["Blue_Creeper", "Enderman", "Energy", "Fire", "Red_Creeper", "Turtle", "Pickaxe", "Firework", "Iron_Golem", "Black", "Blue", "Red", "Purple", "Day Dream", "Chinema", "Fake Wings", "Darkblue L", "Orangest", "White Slash", "Black Butterfly", "Black L", "Double07", "Double07", "Eva", "Demon", "Aceee", "CawPe", "Snake"]
