# Created By VsrStudio
# Config.yml SimpleCkothes Please Don't Delete Anything Here

DeleteSkinAfterQuitting: false

no-permissions: §cYou don't have Permissions for this action!

skin-resetted: §aYour Skin has been resetted!

cape-on: §aYou activated the {name}-Cape!

standard_capes: ["Blue_Creeper", "Enderman", "Energy", "Fire", "Red_Creeper", "Turtle", "Pickaxe", "Firework", "Iron_Golem", "Black", "Blue", "Red", "Purple", "Day Dream", "Chinema", "Fake Wings", "Darkblue L", "Orangest", "White Slash", "Black Butterfly", "Black L", "Double07", "Double07", "Eva", "Demon", "Aceee", "CawPe", "Snake"]

# Particle
Title: "§lSimple Clothes Particle"
Content: "§eSelect your particle"

1:
  Particle:
    Name: 1
    Permission: "particle.flame"
  Button:
    Name: "§l§eFlame Particle\n§rTap To Use"
2:
  Particle:
    Name: 2
    Permission: "particle.entityflame"
  Button:
    Name: "§l§eFire Particle\n§rTap To Use"
3:
  Particle:
    Name: 3
    Permission: "particle.explode"
  Button:
    Name: "§l§eExplode Particle\n§rTap To Use"
4:
  Particle:
    Name: 5
    Permission: "particle.waterdrip"
  Button:
    Name: "§l§eWater Particle\n§rTap To Use"
5:
  Particle:
    Name: 6
    Permission: "particle.lava"
  Button:
    Name: "§l§eLava Particle\n§rTap To Use"
6:
  Particle:
    Name: 8
    Permission: "particle.heart"
  Button:
    Name: "§l§eHeart Particle\n§rTap To Use"
7:
  Particle:
    Name: 9
    Permission: "particle.angryvillager"
  Button:
    Name: "§l§eAngry Particle\n§rTap To Use"
8:
  Particle:
    Name: 10
    Permission: "particle.happyvillager"
  Button:
    Name: "§l§eHappy Particle\n§rTap To Use"
9:
  Particle:
    Name: 16
    Permission: "particle.snowball"
  Button:
    Name: "§l§eSnow Particle\n§rTap To Use"

# Crate
form.menu:
  title: "Crate"
  content: "You have §a{KEY} §fkey" #<=
  open.crate:
    button.name: "Open Crate"
  open.keyshop:
    button.name: "Key Shop"
  exit.menu:
    button.name: "§l§cEXIT"

#Setting reward and message.
#Add permission gift command:
# /sccrate help show all command
# permission add {player} pastepermission
# scrca {player} permission add {player} pastepermission
reward-message: "§l§aCONGRATULATIONS\n§r§7You got §r§a"
reward:
  - name: "§l§e1000 Money"
    commands:
      - "givemoney {player} 1000"
  - name: "§l§e20 Diamonds"
    commands:
      - "give {player} diamond 20"
  - name: "§l§e32 Iron Ingot"
    commands:
      - "give {player} iron_ingot 32"
  - name: "§l§e10 Emerald"
    commands:
      - "give {player} emerald 10"
  - name: "§l§e+ 1 Key"
    commands:
      - "sccrate givekey {player} 1"
  - name: "§l§e5000 Money"
    commands:
      - "givemoney {player} 5000"
  - name: "§l§e64 Wheat"
    commands:
      - "give {player} wheat 64"
  - name: "§l§e32 Potato"
    commands:
      - "give {player} potato 32"
  - name: "§l§e25 Carrot"
    commands:
      - "give {player} carrot 25"

# Paste Permission Here
# Shop
shop:
  wings:
    "demon.wing": 1000
    "kagune.wing": 1500
  capes:
    "Aceee.cape": 5000
    "CawPe.cape": 10000
  hats:
    "tv.hats": 2000
    "frog.hats": 2500
  particles:
    "particle.flame": 1200
    "particle.lava": 1800
